#76: Improve TLS compatibility documentation
exasol/exasol-virtual-schema pull request #77
Opened 2022-06-24 06:14 UTC by redcatbear

Closes #76.

2022-06-24 06:20 UTC, jakobbraun approved these changes

2022-06-24 07:35 UTC, kaklakariada submitted a review, later dismissed
The proposed change is optional.

2022-06-24 07:35 UTC, kaklakariada commented on doc/dialects/exasol.md
> +Older versions (6.2.0 &hellip; 6.2.14 and 7.0.0 &hellip; 7.0.9) automatically fall back to legacy encryption. These versions are outdated anyway. If you still have one of them running, you should sti
```suggestion
Older versions (6.2.0 &hellip; 6.2.14 and 7.0.0 &hellip; 7.0.9) automatically fall back to legacy encryption. These versions are outdated anyway. If you still have one of them running, you should still disable TLS support explicitly by specifying parameter `legacyencryption=1` in the JDBC URL (see details about [supported driver properties](https://docs.exasol.com/db/latest/connect_exasol/drivers/jdbc.htm#SupportedDriverProperties)). This is a visual reminder that TLS won't work with those versions.
```

2022-07-04 13:14 UTC, kaklakariada submitted a review, later dismissed

2022-07-04 13:37 UTC, kaklakariada submitted a review, later dismissed

2022-07-06 12:56 UTC, redcatbear commented on .github/workflows/ci-build.yml
> +              -DtrimStackTrace=false
That must have been an accident. Fixed.

2022-07-07 14:05 UTC, pj-spoelders approved these changes
Looks good!

2022-07-07 15:22 UTC, kaklakariada requested changes

2022-07-07 15:22 UTC, kaklakariada commented on pom.xml
> +                        netty in a way where this cannot be exploited. -->
```suggestion
                        <!-- This is a vulnerability in the transitive netty test dependency introduced by the
                        AWS SDK and in turn by exasol-test-setup-abstraction-java. AWS notes that they handle
                        netty in a way where this cannot be exploited.
                        See https://github.com/aws/aws-sdk-java-v2/issues/3263#issuecomment-1163600532 -->
```

2022-07-08 07:48 UTC, kaklakariada approved these changes

2022-07-08 07:49 UTC, kaklakariada requested changes

2022-07-08 07:49 UTC, kaklakariada commented on doc/changes/changes_6.0.3.md
>  # Exasol Virtual Schema 6.0.3, released 2022-02-??
```suggestion
# Exasol Virtual Schema 6.0.3, released 2022-07-08
```

2022-07-08 08:18 UTC, kaklakariada approved these changes

2022-07-08 08:21 UTC, merged